[package]
name = "qarax"
version = "0.1.0"
authors = ["Benny Zlotnik <bzlotnik@protonmail.com>"]
edition = "2018"

[dependencies]
rocket = "0.4.5"
diesel = { version = "1.4", features = ["postgres", "r2d2", "uuid"] }
diesel_migrations = "1.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
uuid = { version = "0.6.5", features = ["serde", "v4"] }
dotenv = "0.15.0"
tonic = "0.2"
prost = "0.6"
futures = "0.3"
tokio = { version = "0.2", features = ["full"] }
async-stream = "0.2"
anyhow = "1.0"
thiserror = "1.0"
dashmap = "3.11.7"

[dependencies.rocket_contrib]
version = "0.4.5"
default-features = false
features = ["diesel_postgres_pool", "json", "uuid"]

[build-dependencies]
tonic-build = "0.2"

[workspace]
default-members = [".", "qarax-node"]
members = [".", "qarax-node"]
